### ISSUE TITLE
When to create new/unique instances for an asserted class

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/biocode-fims-configurator#5]
After discussion with Brian and Ramona, we looked at two correct ways of expressing phenological stage in Triple form. Essentially, phenological stages (e.g. leaf color) are dependent on individual instances so different leaf colors are different for different plants and thus you cannot apply the same "leaf colored stage" to different plants, or even the same plant on different days.

Method 1: Use blank nodes to express this... This is more compact and probably leads to faster processing.

Method #: Create unique identifiers for each instance of, for example, "leaf colored stage".

Assuming i use Method 1, i will need to research if D2RQ supports blank node development. ALSO, in the relations.csv file will need to create some column that says, effectively "Create blank node for each instance" {True|False}

This issue is a clarification of issue #4

**Comment by rlwalls2008** [comment]
This looks good, John. 

Just to clarify, in case someone else stumbles across this, "leaf color" in this case is shorthand for a "leaf colored stage". The quality leaf color would also require separate instances for each plant that bore the leaf color.

**Comment by stuckyb** [comment]
One other clarification -- you *might* be able to use the same instance of a phenological stage for "the same plant on different days."  Depending on how a stage is defined, an individual plant could participate in the same phenological stage for two or more days.

**Comment by jdeck88** [comment]
This has been solved by using Method #2, creating unique identifiers for each instance of stage.  Blank nodes proved problematic.
